os: linux
dist: focal
language: shell
env:
  global:
    - tf_version=0.15.5 
    - tf_init_cli_options="-input=false" 
    - tf_validation_cli_options="" 
    - tf_plan_cli_options="-lock=false -input=false" 
    - tf_apply_cli_options="-auto-approve -input=false"

branches:
  only:
    - master

before_install:
  - wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
  - unzip terraform_"$tf_version"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$tf_version"_linux_amd64.zip

stages:
  - lint
  - test
  - release

jobs:
  include:
    - stage: lint
#      if: type = pull_request
      script:
        - echo "Checking syntax"
        - terraform fmt -check

    - stage: test
      # Only run terraform validate and plan state if within a pull request
#     if: type = pull_request
      script:
        - echo "Executing Terraform Plan on pull request code"
        - cd examples/terraform/
        - terraform init $tf_init_cli_options
        - terraform validate $tf_validation_cli_options
        - terraform plan $tf_plan_cli_options

    - stage: release
      if: branch = master
      language: node_js
      node_js:
        - 17
      install:
        - pip install mkdocs-material
        - npm install @semantic-release/github -D
        - npm install @semantic-release/changelog -D
      script:
        - npx semantic-release

